<?php
/**
  * FizzBuzz
  *
  * Write a PHP script that prints all integer values from 1 to 100.
  *
  * For multiples of three output "Fizz" instead of the value and for the
  * multiples of five output "Buzz". Values which are multiples of both three
  * and five should output as "FizzBuzz".
  *
  * @author  Srikanth Matheesh <phpsri@gmail.com>
  *
  * @version 1.0
  *
  * @since 1.0
  *
  */
	$count = 1;

    while ($count <= 100) {

        // Initiate variable of output
        $output = null;

        // Check if $count is multiples of three
        if ($count%3 === 0 && $count != 0) {
            $output = "Fizz";
        }

        // Check if $count is multiples of three and five
        if ($count%5 === 0 && $count != 0) {
            $output .= "Buzz"; // concatenate string if $count is multiples of 3
        }

        // Prints the output generated by previous conditions
        echo (!isset($output)) ? "{$count} === {$count}\n" : "{$count} === {$output}\n";

        $count++;
    }
?>
